services:
  web:
    build: .
    container_name: sipena-container
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    user: root
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             chown -R appuser:appuser /app/media /app/staticfiles &&
             exec gosu appuser gunicorn sipena.wsgi:application --bind 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume:
